- operations/README.md
- operations/defaults/main.yml
- operations/meta/main.yml
- operations/tasks/disable-node.yml
- operations/tasks/enable-node.yml
- operations/tasks/main.yml
- operations/tasks/upgrade-docker.yml
Introduce a sub-role, `operations`, to host common workflows related to an osbs managed cluster.
> Upgrade docker workflow

- templates/client-config-secret.conf.j2
- tests/files/expected-client-config-secret.conf
- tests/group_vars/masters.yml
- tests/test.yml
> update client config secret with auto build node selector

- operations/README.md
- operations/defaults/main.yml
- operations/tasks/main.yml
- operations/tasks/update-node-selector-labels.yml
> task for updating labels

- defaults/main.yml
- tasks/orchestrator.yml
- templates/osbs-buildroot-imagestream.yml.j2
> task for creating imagestream for buildroot

- defaults/main.yml
- tasks/orchestrator.yml
- templates/osbs-buildroot-imagestream.yml.j2
> imagestream name change

- templates/osbs-buildroot-imagestream.yml.j2
> fix imagestream template

- tasks/orchestrator.yml
> fix update imagestream tag

- defaults/main.yml
- templates/reactor-config-secret.yml.j2
Signed-off-by: Bret Fontecchio <bfontecc@redhat.com>
> Update reactor-config-secret to include odcs configurations

- templates/reactor-config-secret.yml.j2
> correct yaml format for signing intents

- templates/reactor-config-secret.yml.j2
> fix for correct yaml format for signing intents

- operations/tasks/tag-buildroot.yml
> fix additional and in where

- tasks/main.yml
> conditional namespace creation

- tasks/orchestrator.yml
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Specify namespace for import-image

- operations/tasks/tag-buildroot.yml
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Specify namespace for oc tag command

- filter_plugins/with_isolated_workers.py
- tests/files/expected-reactor-config-map-ppc64le-on-premise.yml
- tests/files/expected-reactor-config-map-scratch-ppc64le-on-premise.yml
- tests/files/expected-reactor-config-map-scratch-x86-64-aws.yml
- tests/files/expected-reactor-config-map-scratch-x86-64-azure.yml
- tests/files/expected-reactor-config-map-scratch-x86-64-on-premise.yml
- tests/files/expected-reactor-config-map-x86-64-aws.yml
- tests/files/expected-reactor-config-map-x86-64-azure.yml
- tests/files/expected-reactor-config-map-x86-64-on-premise.yml
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Fix syntax for worker specific config maps

- defaults/main.yml
- templates/build-pruner-cronjob.yaml.j2
> batch queue name for pruner cronjob is variable

- defaults/main.yml
> fix pruner batch queue name

- defaults/main.yml
> more heavier pruning of openshift builds

- tasks/orchestrator.yml
> import-image message changed in openshift 3.11

- operations/defaults/main.yml
- operations/tasks/override-systemd.yml
> set DefaultLimitNOFILE for systemd in override-systemd task

- operations/defaults/main.yml
> increase DefaultLimitNOFILE even further

- README.md
- defaults/main.yml
- tasks/orchestrator.yml
- templates/client-config-secret.conf.j2
- tests/files/expected-client-config-secret.conf
- tests/group_vars/masters.yml
- tests/test.yml
> return minimal client_config_secret

- defaults/main.yml
- tasks/pruner.yml
> 2nd build-pruner job, which deletes builds which are older than 720h

- defaults/main.yml
- templates/cronjob.yaml.j2
> don't use to_yaml

- templates/cronjob.yaml.j2
> generate list in jinja

- templates/remove-unused-istags.sh.j2
> fix remove-unused-istags script

- templates/prune-config-maps.sh.j2
> fix delete command in prune config-maps tempalate

- templates/client-config-secret.conf.j2
> make code compatible with python3

- tasks/main.yml
> Don't add any permissions explicitly to osbs_service_accounts

- README.md
- tasks/configure_namespace.yml
Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>
> Parametrize pipelinerun pruning

- README.md
- tasks/configure_namespace.yml
This allows to specify rolebindings for Groups and
Users as well
CLOUDBLD-7984
Signed-off-by: mkosiarc <mkosiarc@redhat.com>
> Make creating rolebindings more general

- README.md
- tasks/configure_namespace.yml
- templates/pipeline_run_pruner.sh
completed certain time ago
* CLOUDBLD-8142
> pipeline run cleaner removes only finished pipeline runs, which

- README.md
- defaults/main.yml
- tasks/configure_namespace.yml
> create new cronjob for remote hosts zombie slots pruning

- README.md
- tasks/configure_namespace.yml
> add remote host auth secret to zombie slots pruner cronjob

- tasks/configure_namespace.yml
> fix variable name zombie_slots_pruner_remote_host_auth_mount_path

- templates/client-config-secret.conf.j2
> add worker deadlines to osbs client config secret

- .github/workflows/linters.yaml
- meta/main.yml
- tasks/configure_namespace.yml
- tasks/main.yml
Older versions run with unsupported nodejs
Signed-off-by: Martin Basti <mbasti@redhat.com>
> workflow: use checkout action version 3

- .github/workflows/kics.yaml
KICS - Keeping Infrastructure as Code Secure
Opensource tool for detecting flaws in infrastructure code
Signed-off-by: Martin Basti <mbasti@redhat.com>
> GH Actions: Add KICS
